# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cant_product',
            field=models.IntegerField(),
        ),
    ]
