# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20170625_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
