# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20170628_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 3, 41, 2, 856211)),
        ),
    ]
