# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0005_auto_20170628_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2017, 6, 29, 13, 35, 8, 535331)),
        ),
    ]
